# Change these first
owner: altkennyh2l # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
  - name: Google
    url: https://www.google.com
  - name: Minecraft Server Map Service (Shotanokitou)
    url: "http://mc.komattamode.com:33010/"
  - name: Minecraft Server (UmaibouKoubou)
    check: "tcp-ping"
    url: mc.komattamode.com
    port: 33008
  - name: Minecraft Server (Shotanokitou)
    check: "tcp-ping"
    url: mc.komattamode.com
    port: 33009
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.kinokonoko.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime | Kinokonoko.io
  theme: dark
  introTitle: "Is everything okay?"
  introMessage: This uptime monitor listed a few things that I have control over (Well, of course not Google). If you are facing problem with any of them, contact me via [@altkennyh2l](https://twitter.com/altkennyh2l).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  workflowSchedule:
    graphs: "*/5 * * * *"
    responseTime: "*/5 * * * *"
    staticSite: "*/5 * * * *"
    summary: "*/5 * * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
